### ISSUE TITLE
Allow Ordering By Translations of Fields

### ISSUE THREAD

**Issue by LatidoReMe** [MagiCircles/MagiCircles#86]
For example, if a user speaks Russian, developers should be able to make it ordered (not only shown) in Russian. There might be a workaround to this currently in the framework, but any current method is not very straightforward, and probably isn't worth the effort.

Making it so that developers can attach a t_ or similar prefix to the field so that it'll do it per language would be really nice! Stuff like event titles or name ordering can be made more useful, and it would increase the potential of filters overall.

While it ain't as important, I'd also suggest seeing if you could make the ordering directly related to an overridable value such as t_name or similar, that way developers can modify the defaults of these translated ordering fields to make more sense overall!

**Comment by db0company** [comment]
The ordering is done by MySQL in the query and the translations are stored in JSON within a text field. MySQL just treats it as a text field and is not able to parse the content of the JSON, so it's not possible to make queries that use the values within the JSON besides matching the content ("that text contains "ja" so we know the Japanese value is in there"). So that's not possible unless we give up on using JSON and we-do the whole translation thing which I'm not willing to do.
